In [3]:
import numpy as np

#np version
print(np.__version__)

#array
arr = np.array([1,2,3])
print(arr)


1.18.5
[1 2 3]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [20]:
#scalar
arr = np.array(42)
print(arr)

#1D array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

#2D array
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
arr.shape

#3D array
arr=np.array([[[1,2,3,4],[4,5,6,5]]])
print(arr)
print(arr.shape)
arr[0][1][3]

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3 4]
  [4 5 6 5]]]
(1, 2, 4)


5

In [21]:
#number dimension
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [25]:
#create array with 5 dimension
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)
print(arr.shape)
print(arr[0][0][0][0][0])
print(arr[0][0][0][0][1])
print(arr[0][0][0][0][2])
print(arr[0][0][0][0][3])


[[[[[1 2 3 4]]]]]
number of dimensions : 5
(1, 1, 1, 1, 4)
1
2
3
4


In [26]:
#Get third and fourth elements from the following array and add them.
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [27]:
#Print the last element from the 2nd dim

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [28]:
#array slicing
#[start:end:step]

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print('Slice elements from index 1 to index 5 from the following array:',arr[1:5])
print('Slice elements from index 4 to the end of the array:',arr[4:])
print('Slice elements from the beginning to index 4 (not included):',arr[:4])
print('Slice from the index 3 from the end to index 1 from the end:',arr[-3:-1])
print('Return every other element from index 1 to index 5:',arr[1:5:2])
print('Return every other element from the entire array:',arr[::2])

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('From the second element, slice elements from index 1 to index 4 (not included):',arr[1, 1:4])
print('From both elements, return index 2:',arr[0:2, 2])
print('From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:',arr[0:2, 1:4])



Slice elements from index 1 to index 5 from the following array: [2 3 4 5]
Slice elements from index 4 to the end of the array: [5 6 7]
Slice elements from the beginning to index 4 (not included): [1 2 3 4]
Slice from the index 3 from the end to index 1 from the end: [5 6]
Return every other element from index 1 to index 5: [2 4]
Return every other element from the entire array: [1 3 5 7]
From the second element, slice elements from index 1 to index 4 (not included): [7 8 9]
From both elements, return index 2: [3 8]
From both elements, slice index 1 to index 4 (not included), this will return a 2-D array: [[2 3 4]
 [7 8 9]]


In [31]:
#array datatype
#i - integer
#b - boolean
#u - unsigned integer
#f - float
#c - complex float
#m - timedelta
#M - datetime
#O - object
#S - string
#U - unicode string
#V - fixed chunk of memory for other type ( void )


arr = np.array([1, 2, 3, 4])

print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

#Create an array with data type string:
arr = np.array([1, 2, 3, 4], dtype='S')

print('Create an array with data type string:',arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

int64
<U6
Create an array with data type string: [b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32


In [32]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [33]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [34]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [35]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [39]:
#Array Copy vs View

#Make a copy, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print('COPY ',x)

#######################
#Make a view, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print('VIEW', x)
#########################3
#Make a view, change the view, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print('VIEW CHANGE ',x)

[42  2  3  4  5]
COPY  [1 2 3 4 5]
[42  2  3  4  5]
VIEW [42  2  3  4  5]
[31  2  3  4  5]
VIEW CHANGE  [31  2  3  4  5]


In [40]:


arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
