In [3]:
import numpy as np

#np version
print(np.__version__)

#array
arr = np.array([1,2,3])
print(arr)


1.18.5
[1 2 3]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [20]:
#scalar
arr = np.array(42)
print(arr)

#1D array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

#2D array
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
arr.shape

#3D array
arr=np.array([[[1,2,3,4],[4,5,6,5]]])
print(arr)
print(arr.shape)
arr[0][1][3]

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3 4]
  [4 5 6 5]]]
(1, 2, 4)


5

In [21]:
#number dimension
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [24]:
#create array with 5 dimension
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)
print(arr.shape)
print(arr[0][0][0][0][0])
print(arr[0][0][0][0][1])
print(arr[0][0][0][0][2])
print(arr[0][0][0][0][3])


[[[[[1 2 3 4]]]]]
number of dimensions : 5
(1, 1, 1, 1, 4)
1
2
3
4


IndexError: index 1 is out of bounds for axis 0 with size 1