In [3]:
import numpy as np

#np version
print(np.__version__)

#array
arr = np.array([1,2,3])
print(arr)


1.18.5
[1 2 3]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [20]:
#scalar
arr = np.array(42)
print(arr)

#1D array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

#2D array
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
arr.shape

#3D array
arr=np.array([[[1,2,3,4],[4,5,6,5]]])
print(arr)
print(arr.shape)
arr[0][1][3]

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3 4]
  [4 5 6 5]]]
(1, 2, 4)


5

In [21]:
#number dimension
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [25]:
#create array with 5 dimension
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)
print(arr.shape)
print(arr[0][0][0][0][0])
print(arr[0][0][0][0][1])
print(arr[0][0][0][0][2])
print(arr[0][0][0][0][3])


[[[[[1 2 3 4]]]]]
number of dimensions : 5
(1, 1, 1, 1, 4)
1
2
3
4


In [26]:
#Get third and fourth elements from the following array and add them.
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [27]:
#Print the last element from the 2nd dim

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [28]:
#array slicing
#[start:end:step]

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print('Slice elements from index 1 to index 5 from the following array:',arr[1:5])
print('Slice elements from index 4 to the end of the array:',arr[4:])
print('Slice elements from the beginning to index 4 (not included):',arr[:4])
print('Slice from the index 3 from the end to index 1 from the end:',arr[-3:-1])
print('Return every other element from index 1 to index 5:',arr[1:5:2])
print('Return every other element from the entire array:',arr[::2])

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('From the second element, slice elements from index 1 to index 4 (not included):',arr[1, 1:4])
print('From both elements, return index 2:',arr[0:2, 2])
print('From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:',arr[0:2, 1:4])



Slice elements from index 1 to index 5 from the following array: [2 3 4 5]
Slice elements from index 4 to the end of the array: [5 6 7]
Slice elements from the beginning to index 4 (not included): [1 2 3 4]
Slice from the index 3 from the end to index 1 from the end: [5 6]
Return every other element from index 1 to index 5: [2 4]
Return every other element from the entire array: [1 3 5 7]
From the second element, slice elements from index 1 to index 4 (not included): [7 8 9]
From both elements, return index 2: [3 8]
From both elements, slice index 1 to index 4 (not included), this will return a 2-D array: [[2 3 4]
 [7 8 9]]


In [31]:
#array datatype
#i - integer
#b - boolean
#u - unsigned integer
#f - float
#c - complex float
#m - timedelta
#M - datetime
#O - object
#S - string
#U - unicode string
#V - fixed chunk of memory for other type ( void )


arr = np.array([1, 2, 3, 4])

print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

#Create an array with data type string:
arr = np.array([1, 2, 3, 4], dtype='S')

print('Create an array with data type string:',arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

int64
<U6
Create an array with data type string: [b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32


In [32]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [33]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [34]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [35]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [39]:
#Array Copy vs View

#Make a copy, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print('COPY ',x)

#######################
#Make a view, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print('VIEW', x)
#########################3
#Make a view, change the view, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print('VIEW CHANGE ',x)

[42  2  3  4  5]
COPY  [1 2 3 4 5]
[42  2  3  4  5]
VIEW [42  2  3  4  5]
[31  2  3  4  5]
VIEW CHANGE  [31  2  3  4  5]


In [41]:
#As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

#Every NumPy array has the attribute base that returns None if the array owns the data.

#Otherwise, the base  attribute refers to the original object.

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [42]:
#The shape of an array is the number of elements in each dimension.
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [43]:
#Convert the following 1-D array with 12 elements into a 2-D array.

#The outermost dimension will have 4 arrays, each with 3 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [45]:
#Convert the following 1-D array with 12 elements into a 3-D array.

#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [44]:
#We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [46]:

#Check if the returned array is a copy or a view:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)
#The example above returns the original array, so it is a view.

[1 2 3 4 5 6 7 8]


In [47]:
#Convert 1D array with 8 elements to 3D array with 2x2 elements:

#You are allowed to have one "unknown" dimension.

#Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

#Pass -1 as the value, and NumPy will calculate this number for you.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [48]:
#Flattening array means converting a multidimensional array into a 1D array.

#We can use reshape(-1) to do this.

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [50]:
#Iterate on the elements of the following 1-D array:

arr = np.array([1, 2, 3])

for x in arr:
  print(x)


arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)



arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)


arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)




1
2
3
[1 2 3]
[4 5 6]
1
2
3
4
5
6
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


In [51]:
#Iterating Arrays Using nditer()

#The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

#Iterating on Each Scalar Element
#In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.


arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

  

1
2
3
4
5
6
7
8


In [52]:
#Iterate through the array as a string:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [53]:
#Iterating With Different Step Size

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [54]:

#Enumerated Iteration Using ndenumerate()
#Enumeration means mentioning sequence number of somethings one by one.

#Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.


arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
